use AssistiveChat;
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("genderList", "Male/Man<SEP>Female/Woman<SEP>Trans male/Trans man<SEP>Trans female/Trans woman<SEP>Genderqueer/Gender non-conforming/Gender non-binary<SEP>A gender identity not listed here. Please specify", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("raceList", "Hispanic/Latino<SEP>Black or African American, Non-Hispanic<SEP>White, Non-Hispanic<SEP>American Indian or Alaska Native, Non-Hispanic<SEP>Asian, Non-Hispanic<SEP>Native Hawaiian or other Pacific Islander, Non-Hispanic<SEP>Two or more races, Non-Hispanic<SEP>Race and/or Ethnicity Unknown<SEP>Prefer not to answer", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("nativeLanguageList", "English<SEP>Chinese – Mandarin<SEP>Chinese – Cantonese<SEP>French<SEP>German<SEP>Italian<SEP>Korean<SEP>Russian<SEP>Spanish<SEP>Vietnamese<SEP>Hindi<SEP>Portuguese<SEP>Arabic<SEP>Others – Specify", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("nationalityList", "Afghanistan<SEP>Albania<SEP>Algeria<SEP>Andorra<SEP>Angola<SEP>Antigua and Barbuda<SEP>Argentina<SEP>Armenia<SEP>Australia<SEP>Austria<SEP>Azerbaijan<SEP>The Bahamas<SEP>Bahrain<SEP>Bangladesh<SEP>Barbados<SEP>Belarus<SEP>Belgium<SEP>Belize<SEP>Benin<SEP>Bhutan<SEP>Bolivia<SEP>Bosnia and Herzegovina<SEP>Botswana<SEP>Brazil<SEP>Brunei<SEP>Bulgaria<SEP>Burkina Faso<SEP>Burundi<SEP>Cambodia<SEP>Cameroon<SEP>Canada<SEP>Cape Verde<SEP>Central African Republic<SEP>Chad<SEP>Chile<SEP>China<SEP>Colombia<SEP>Comoros<SEP>Congo, Republic of the<SEP>Congo, Democratic Republic of the<SEP>Costa Rica<SEP>Cote d'Ivoire<SEP>Croatia<SEP>Cuba<SEP>Cyprus<SEP>Czech Republic<SEP>Denmark<SEP>Djibouti<SEP>Dominica<SEP>Dominican Republic<SEP>East Timor (Timor-Leste)<SEP>Ecuador<SEP>Egypt<SEP>El Salvador<SEP>Equatorial Guinea<SEP>Eritrea<SEP>Estonia<SEP>Ethiopia<SEP>Fiji<SEP>Finland<SEP>France<SEP>Gabon<SEP>The Gambia<SEP>Georgia<SEP>Germany<SEP>Ghana<SEP>Greece<SEP>Grenada<SEP>Guatemala<SEP>Guinea<SEP>Guinea-Bissau<SEP>Guyana<SEP>Haiti<SEP>Honduras<SEP>Hungary<SEP>Iceland<SEP>India<SEP>Indonesia<SEP>Iran<SEP>Iraq<SEP>Ireland<SEP>Israel<SEP>Italy<SEP>Jamaica<SEP>Japan<SEP>Jordan<SEP>Kazakhstan<SEP>Kenya<SEP>Kiribati<SEP>Korea, North<SEP>Korea, South<SEP>Kosovo<SEP>Kuwait<SEP>Kyrgyzstan<SEP>Laos<SEP>Latvia<SEP>Lebanon<SEP>Lesotho<SEP>Liberia<SEP>Libya<SEP>Liechtenstein<SEP>Lithuania<SEP>Luxembourg<SEP>Macedonia<SEP>Madagascar<SEP>Malawi<SEP>Malaysia<SEP>Maldives<SEP>Mali<SEP>Malta<SEP>Marshall Islands<SEP>Mauritania<SEP>Mauritius<SEP>Mexico<SEP>Micronesia, Federated States of<SEP>Moldova<SEP>Monaco<SEP>Mongolia<SEP>Montenegro<SEP>Morocco<SEP>Mozambique<SEP>Myanmar (Burma)<SEP>Namibia<SEP>Nauru<SEP>Nepal<SEP>Netherlands<SEP>New Zealand<SEP>Nicaragua<SEP>Niger<SEP>Nigeria<SEP>Norway<SEP>Oman<SEP>Pakistan<SEP>Palau<SEP>Panama<SEP>Papua New Guinea<SEP>Paraguay<SEP>Peru<SEP>Philippines<SEP>Poland<SEP>Portugal<SEP>Qatar<SEP>Romania<SEP>Russia<SEP>Rwanda<SEP>Saint Kitts and Nevis<SEP>Saint Lucia<SEP>Saint Vincent and the Grenadines<SEP>Samoa<SEP>San Marino<SEP>Sao Tome and Principe<SEP>Saudi Arabia<SEP>Senegal<SEP>Serbia<SEP>Seychelles<SEP>Sierra Leone<SEP>Singapore<SEP>Slovakia<SEP>Slovenia<SEP>Solomon Islands<SEP>Somalia<SEP>South Africa<SEP>South Sudan<SEP>Spain<SEP>Sri Lanka<SEP>Sudan<SEP>Suriname<SEP>Swaziland<SEP>Sweden<SEP>Switzerland<SEP>Syria<SEP>Taiwan<SEP>Tajikistan<SEP>Tanzania<SEP>Thailand<SEP>Togo<SEP>Tonga<SEP>Trinidad and Tobago<SEP>Tunisia<SEP>Turkey<SEP>Turkmenistan<SEP>Tuvalu<SEP>Uganda<SEP>Ukraine<SEP>United Arab Emirates<SEP>United Kingdom<SEP>United States of America<SEP>Uruguay<SEP>Uzbekistan<SEP>Vanuatu<SEP>Vatican City (Holy See)<SEP>Venezuela<SEP>Vietnam<SEP>Yemen<SEP>Zambia<SEP>Zimbabwe", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("educationList", "Some high school<SEP>High school diploma or equivalent<SEP>Post High School Vocational training<SEP>Some College or Associate's degree<SEP>Bachelor's degree<SEP>Master's degree<SEP>Doctorate degree", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("fieldOfEducationList", "Natural and Physical Sciences (E.g. Mathematics, Astronomy, Chemical, Earth, Biological, Other Natural and Physical Sciences)<SEP>Information Technology (E.g. Computer Science, Information Systems, Other Information Technology)<SEP>Engineering and Related Technologies (E.g. Aeronautics, Manufacturing, Food Technology, Materials Science, Plant and Machine Maintenance)<SEP>Architecture and Building (E.g. Architecture and Urban Environment, Building)<SEP>Agriculture, Environmental and Related Studies (E.g. Crop Production, Animal Production and Management, Environmental Impact and Assessment)<SEP>Health (E.g. Disease Processes and Mechanisms, Restoration and Maintenance of Health, Diagnosis, Principles and Practices of Public Health)<SEP>Education (E.g. Curriculum Development, Processes of Learning and Skill Acquisition, Teaching Methods)<SEP>Management and Commerce (E.g. Administration, Human Resources, Sales, Marketing, Financial Management, Human Behaviour and Time Management)<SEP>Society and Culture (E.g. Belief and Value Systems, Cultural Expression, Human Development, Politics, Social Organisation & Research)<SEP>Creative Arts (E.g. Performing Arts, Visual Arts and Crafts, Graphic and Design Studies, Communication and Media Studies, Other Creative Arts)<SEP>Food, Hospitality and Personal Services (E.g. Food and Hospitality, Personal Services, Beauty Care, Hair Cutting & Styling, Housekeeping)<SEP>Mixed Field Programs (E.g. General Education, Social & Employment Skills, Literacy & Numeracy Skills, Social & Workplace Relationships)", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("maritalStatusList", "Never married<SEP>Married<SEP>Widowed<SEP>Divorced<SEP>Separated", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("employementStatusList", "Employed Full-Time<SEP>Employed Part-Time<SEP>Student<SEP>Unemployed", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("workIndustryList", "Computer and Information Systems (E.g. Computer Science, Information Systems, Other Information Technology)<SEP>Agriculture, Forestry, Fishing and Hunting<SEP>Mining, Quarrying, and Oil and Gas Extraction<SEP>Utilities (E.g. Electric Power Generation, Transmission, Distribution, Natural Gas Distribution, Water, Sewage, Irrigation)<SEP>Construction<SEP>Manufacturing<SEP>Wholesale Trade<SEP>Retail Trade<SEP>Transportation and Warehousing (E.g. Urban Transit Systems, Mixed Mode Transit Systems, School and Employee Bus Transportation)<SEP>Information  (E.g. Publisher, Motion Picture, Telecommunications, Data Processing, Hosting, News Syndicates, Libraries and Archives)<SEP>Finance and Insurance<SEP>Real Estate and Rental and Leasing<SEP>Professional, Scientific, and Technical Services (E.g. Legal Services, Offices of Lawyers, Tax Preparation Services, Industrial Design Services)<SEP>Management of Companies and Enterprises (E.g. Offices of Bank Holding Companies, Management of Companies and Enterprises)<SEP>Administrative Support, Waste Management, Remediation Services (E.g. Employment, Support Services, Private Mail Centers, Telemarketing Bureaus)<SEP>Educational Services<SEP>Health Care and Social Assistance<SEP>Arts, Entertainment, and Recreation<SEP>Accommodation and Food Services (E.g. Hotels, Casinos, Caterers, Restaurants, Drinking Places (Alcoholic Beverages))<SEP>Public Administration (E.g. Executive Offices, Legislative Bodies, Justice, Public Order, National Security, International Affairs)<SEP>Other Services (E.g. Automotive & Electronics Repair & Maintenance, Personal Care Services, Cemeteries, Pet Care, Parking Lots)", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("disabilityList", "Yes; Specify if yes<SEP>No", NOW(), NOW());
INSERT INTO demographicQuestionnaire (ListName, ListValues, CreatedAt, UpdatedAt)
VALUES ("recruitedList", "Events & Activities at Illinois Tech<SEP>Referred by a friend or a colleague<SEP>Contacted by an associate working on this application<SEP>Search Engine<SEP>Social Media<SEP>Blog / Publication", NOW(), NOW());
